image: openjdk:10-jre-slim

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean build -x javadoc

build:
  stage: build
  script:
    - pwd
    - ls -lrt
    - gradlew clean build -x javadoc

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public/api
    - cp -R docs/javadoc/* public/api
    - mkdir -p public/coverage
    - cp -R build/reports/tests/* public/
  artifacts:
    paths:
      - public
  only:
    - master
